# Site settings
title: Fabien Salathe Website
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Fabien Salathe Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 0xbafs
github_username:  bafs

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
